name: tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - release/**

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [8.1, 8.2, 8.3, 8.4]
                laravel: [10.*, 11.*, 12.*]
                exclude:
                    - php: 8.1
                      laravel: 11.*
                    - php: 8.1
                      laravel: 12.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                  composer update --prefer-dist --no-interaction --no-progress

            - name: Execute pint
              run: vendor/bin/pint --test

            - name: Execute tests
              run: vendor/bin/pest --ci --parallel
